### ISSUE TITLE
Several compile warnings

### ISSUE THREAD

**Issue by kokujin** [valeriansaliou/node-fast-ratelimit#10]
node-fast-ratelimit emits sevral errors when being compiled, for example:

`../node_modules/nan/nan_implementation_12_inl.h:340:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();`

`../node_modules/nan/nan.h:1066:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();`

`../node_modules/nan/nan.h:1080:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);`

`9 warnings generated.
  SOLINK_MODULE(target) Release/native.node`

Maybe its time that @valeriansaliou had a chat with the maintainer of the hashtable module?

**Comment by valeriansaliou** [comment]
Can you provide more details on the platform you're getting those warnings on?

**Comment by kokujin** [comment]
These warnings are emitted when installing the rate limiter hook for the feathers.js framework. The hook uses node-fast-ratelimit as a dependency [feathers-hooks-ratelimit](https://github.com/AZaviruha/feathers-hooks-ratelimit)

**Comment by valeriansaliou** [comment]
What's your OS, what's your compiler? (GCC? Which version?)

**Comment by kokujin** [comment]
I am using an Apple device, OSX 10.13.6, the compiler is Xcode 10.1, Build version 10B61. I presume. The warnings are also emitted on my colleagues Windows device.

**Comment by valeriansaliou** [comment]
Gotcha, I'll have a look when I have time :)

**Comment by kokujin** [comment]
Great! Thanks

**Comment by valeriansaliou** [comment]
Hello there! I've fixed that in `v3.0.0`, using the JS-native Map object, which has as well be measured in my tests to be faster anyway. This new version does not compile any dependencies anymore, fixing this issue.
