### ISSUE TITLE
Does not work with node 12

### ISSUE THREAD

**Issue by KidkArolis** [valeriansaliou/node-fast-ratelimit#15]
The native `hashtable` code does not compile in Node 12. For anyone bumping into that issue, I've published a functionally equivalent fork that uses ES `Map` instead of the `hashtable` package under:

`npm install @kidkarolis/not-so-fast`

https://github.com/KidkArolis/not-so-fast

**Comment by valeriansaliou** [comment]
Thanks, I'll backport this to `node-fast-ratelimit`. Reason for me not fixing anything so far is that we use the library for Crisp (crisp.chat), which is running Node LTS versions (v10).

**Comment by electic** [comment]
Great component. I am having the same issue. Appreciate a backport.

**Comment by rdewolff** [comment]
Facing the same issue with Node 12. 

Any update on porting this on the repo @valeriansaliou ?

**Comment by KidkArolis** [comment]
For what it's worth, I'm still using the fork linked above in production. Although, the way I forked it doesn't make it easy to diff the two packages easily 🤔.

**Comment by valeriansaliou** [comment]
Hello there! I've fixed that in `v3.0.0`, using the JS-native Map object, which has as well be measured in my tests to be faster anyway. Note that support for NodeJS older than `6.0.0` has been dropped though.
