### ISSUE TITLE
Hashtable dependency does not build correctly when using "Yarn add"

### ISSUE THREAD

**Issue by wdmtech** [valeriansaliou/node-fast-ratelimit#3]
Just noting this in case someone else tries it!

**Comment by valeriansaliou** [comment]
I do accept PRs 🙂

**Comment by wdmtech** [comment]
I'm not sure if it's because it was compiled on Windows - I'll check on my mac tomorrow.

**Comment by simlu** [comment]
Same here. Does not seem to work on windows unfortunately...

**Comment by simlu** [comment]
Finally fixed this by installing `npm install -g windows-build-tools` with elevated privileges (Reference https://superuser.com/questions/1032689/how-do-i-add-vcbuild-exe-to-windows-10-w-o-visual-studio)

**Comment by simlu** [comment]
Would you mind adding that to the docs please?

Also I'm getting some warnings, but will post as separate issue.

**Comment by valeriansaliou** [comment]
Added to the README, thanks!
