### ISSUE TITLE
Hashmap doesn't seem to get uninstalled correct

### ISSUE THREAD

**Issue by simlu** [valeriansaliou/node-fast-ratelimit#5]
An empty folder remains for some reason. Maybe this is expected for native dependencies?

**Comment by valeriansaliou** [comment]
Can I have more info. on this?

**Comment by simlu** [comment]
Sure!
(1) `npm install fast-ratelimit`
(2) run code using the ratelimiter
(3) `npm uninstall fast-ratelimit`

The hashtable folder does not get cleaned up completely in this case. I'm wondering if some files can not be deleted b/c they are loaded by windows.

Might not be related to you project but just a general observation.

**Comment by valeriansaliou** [comment]
Hello there! I've fixed that in `v3.0.0`, using the JS-native Map object, which has as well be measured in my tests to be faster anyway. This new version does not compile any dependencies anymore, fixing this issue.
