### ISSUE TITLE
FYI: Simple cross platform rate limiter

### ISSUE THREAD

**Issue by simlu** [valeriansaliou/node-fast-ratelimit#6]
Spend way to much time getting the compiled code to work across platforms, so I ended up writing my own (very simple) rate limiter:

https://github.com/simlu/lambda-rate-limiter

**Comment by valeriansaliou** [comment]
Hello there! I've fixed that in `v3.0.0`, using the JS-native Map object, which has as well be measured in my tests to be faster anyway. This new version does not compile any dependencies anymore, fixing this issue.
